name: plantrecogniser
description: Plant recogniser in Flutter using TensorFlow Lite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  image: ^3.0.2
  image_picker: ^0.8.6
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SquadaOne
      fonts:
        - asset: assets/SquadaOne-Regular.ttf
    - family: ContrailOne
      fonts:
        - asset: assets/ContrailOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Light.ttf
  
  assets:
    - assets/
